# Models

Three analyses, one pipeline each:

1. **Union density** (blue charts)
2. **Electoral democracy** (orange charts)
3. **Electoral democracy without V-Dem predictors** (green charts)

Each section fits an OLS on the training countries for its coefficients, then scores OLS and a random forest with **nested**, grouped cross-validation: the forest is re-tuned inside every outer fold, using only that fold's training countries, so no country it is scored on ever influenced its settings. Permutation importances come from the same folds.

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
# OLS is imported directly: statsmodels.api also loads statsmodels.tsa.statespace,
# whose compiled _conventional DLL is blocked by Windows Application Control
from statsmodels.regression.linear_model import OLS
from statsmodels.tools.tools import add_constant
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error
from sklearn.model_selection import GridSearchCV, GroupKFold, GroupShuffleSplit
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [2]:
# NOTE: tuning.ipynb has an identical copy of this block
df = pd.read_csv("../data/merged.csv")

ID_COLS = ["iso3", "country", "Unnamed: 0"]
DROP = ["emp_services_pct",     # emp shares sum to exactly 100
        "services_va_pct_gdp",  # value-added shares nearly sum to 100
        "emp_pop_ratio",        # ≈ lfp_rate × (1 − unemployment)
        "self_employed_pct",    # r = 0.996 with vulnerable_emp_pct
        "exports_pct_gdp",      # r = 0.987 with trade_pct_gdp
        "liberal_democracy"]    # r = 0.981 with electoral_democracy
# V-Dem builds electoral_democracy (v2x_polyarchy) from freedom_of_association
# (v2x_frassoc_thick), which is itself built from cso_entry_exit and
# cso_repression; civil_society_index shares those two inputs (codebook v16).
# Predicting democracy from them would be predicting the index from its parts
DEM_INGREDIENTS = ["freedom_of_association", "cso_entry_exit",
                   "cso_repression", "civil_society_index"]
# every V-Dem column in merged.csv (VDEM_NAMES in cleaning.ipynb), for the
# democracy model with no V-Dem predictors at all
VDEM_COLS = ["freedom_of_association", "civil_society_index", "electoral_democracy",
             "liberal_democracy", "cso_repression", "cso_entry_exit",
             "egalitarian_component", "equal_resource_distribution",
             "power_by_socioeconomic_position", "state_mass_org_engagement",
             "regime_support_working_class", "govt_ideology_socialist"]
# predictors from the union-density literature -- Ghent system, state-run vs
# independent unions, labour's political power -- used by the union density
# model only
UNION_ONLY = ["ghent", "state_mass_org_engagement",
              "regime_support_working_class", "govt_ideology_socialist"]

cols_union = [c for c in df if c not in ID_COLS + ["union_density"] + DROP]
cols_dem = [c for c in df if c not in ID_COLS + ["electoral_democracy"] + DROP + DEM_INGREDIENTS + UNION_ONLY]
cols_dem_novdem = [c for c in df if c not in ID_COLS + VDEM_COLS + DROP + UNION_ONLY]

# rows must be complete in every column except the union-only additions, so
# adding them can't change the democracy analyses or the train/test split. the
# union model drops its own incomplete rows, if any
df = df.dropna(subset=[c for c in df.columns if c not in UNION_ONLY]).reset_index(drop=True)

random_state = 42

# one train/test split: models.ipynb fits its OLS summaries on the training
# rows, and tuning.ipynb tunes on the training countries only. whole countries
# are held out, so no country appears in both halves
splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=random_state)
train_idx, test_idx = next(splitter.split(df, groups=df["iso3"]))
train, test = df.loc[train_idx], df.loc[test_idx]

print(f"train: {len(train):4d} rows, {train['iso3'].nunique():3d} countries")
print(f"test:  {len(test):4d} rows, {test['iso3'].nunique():3d} countries")
print("countries in both:", len(set(train["iso3"]) & set(test["iso3"])))
print(f"\nfeatures -- union density: {len(cols_union)} | democracy: {len(cols_dem)} | "
      f"democracy, no V-Dem: {len(cols_dem_novdem)}")

train:  787 rows,  80 countries
test:   208 rows,  20 countries
countries in both: 0

features -- union density: 39 | democracy: 31 | democracy, no V-Dem: 28

In [3]:
# shared by every section, so each analysis gets exactly the same models,
# scoring, and charts
BLUE, ORANGE, GREEN = "#2a78d6", "#eb6834", "#008300"   # sections 1, 2, 3
MUTED, SURFACE = "#52514e", "#fcfcfb"
CV_REPEATS, CV_FOLDS = 3, 5

# the random forest's settings are searched over this grid (the same one as
# tuning.ipynb) inside every outer CV fold
GRID = {
    "max_features": [0.2, 0.33, 0.5, 1.0],
    "min_samples_leaf": [1, 2, 5, 10],
    "max_samples": [None, 0.7],
}
SEARCH_TREES, FINAL_TREES = 300, 1000


def scale(cols):
    """Scaled training features for the OLS summaries, on the training rows
    that are complete for these columns."""
    rows = train.dropna(subset=cols)
    scaler = StandardScaler().fit(rows[cols])
    return pd.DataFrame(scaler.transform(rows[cols]), columns=cols, index=rows.index)


def tuned_forest(X, y, groups):
    """Grid-search the forest on these rows only, with inner folds grouped by
    country, then refit the winning settings with more trees."""
    search = GridSearchCV(
        RandomForestRegressor(n_estimators=SEARCH_TREES, random_state=random_state, n_jobs=1),
        GRID,
        cv=GroupKFold(CV_FOLDS),
        scoring="neg_root_mean_squared_error",
        n_jobs=-1,
    ).fit(X, y, groups=groups)
    forest = RandomForestRegressor(n_estimators=FINAL_TREES, random_state=random_state,
                                   n_jobs=-1, **search.best_params_)
    return forest.fit(X, y), search.best_params_


def nested_cv(X, y, groups):
    """Scores and permutation importances from nested, grouped cross-validation.

    Outer loop: 5 folds of whole countries, repeated with the countries
    reshuffled, so every country is tested once per repeat. A single
    train/test split would rest on 20 test countries, which is far too few --
    the same model scored anywhere from -2.06 to 0.50 depending on the draw.

    Inner loop: the forest is tuned on the outer fold's training countries
    only, so the countries it is scored on never influenced its settings
    (Neunhoeffer & Sternberg 2019). OLS and the baseline have nothing to tune.
    """
    names = ["baseline", "OLS", "random forest"]
    rows, importances, chosen = [], [], []
    for seed in range(CV_REPEATS):
        oof = {name: np.zeros(len(y)) for name in names}
        # same folds for every model, so the comparison is paired
        cv = GroupKFold(n_splits=CV_FOLDS, shuffle=True, random_state=seed)
        for tr, te in cv.split(X, y, groups):
            X_tr, y_tr, X_te, y_te = X.iloc[tr], y.iloc[tr], X.iloc[te], y.iloc[te]
            forest, best = tuned_forest(X_tr, y_tr, groups.iloc[tr])
            chosen.append(str(best))

            fitted = {
                "baseline": DummyRegressor(strategy="mean").fit(X_tr, y_tr),
                "OLS": make_pipeline(StandardScaler(), LinearRegression()).fit(X_tr, y_tr),
                "random forest": forest,
            }
            for name, model in fitted.items():
                oof[name][te] = model.predict(X_te)

            # importance measured on countries the tuned forest never saw
            r = permutation_importance(forest, X_te, y_te, n_repeats=10,
                                       scoring="neg_root_mean_squared_error",
                                       random_state=0, n_jobs=-1)
            importances.append(pd.Series(r.importances_mean, index=X.columns))

        # pool the out-of-fold predictions and score once per repeat --
        # averaging each fold's R2 instead is dragged down by folds with
        # little spread to explain
        for name in names:
            rows.append({
                "model": name,
                "seed": seed,
                "RMSE": root_mean_squared_error(y, oof[name]),
                "MAE": mean_absolute_error(y, oof[name]),
                "R2": r2_score(y, oof[name]),
            })

    scores = pd.DataFrame(rows)
    table = (scores.groupby("model")[["RMSE", "MAE", "R2"]]
             .agg(["mean", "std"]).round(3)
             .reindex(names))
    print(f"nested {CV_FOLDS}-fold grouped CV, {CV_REPEATS} repeats, "
          f"{len(X)} rows / {groups.nunique()} countries\n")
    print(table.to_string())

    wide = scores.pivot(index="seed", columns="model", values="R2")
    print(f"\nforest beat OLS in {(wide['random forest'] > wide['OLS']).sum()} of {CV_REPEATS} repeats")

    picks = pd.Series(chosen).value_counts()
    print(f"\nforest settings chosen in the {len(chosen)} outer folds "
          f"({len(picks)} different combinations); most common:")
    print(picks.head(3).to_string())
    return scores, pd.DataFrame(importances)


def importance_table(imp):
    return (pd.DataFrame({"mean": imp.mean(), "sd": imp.std(), "folds_positive": (imp > 0).sum()})
            .sort_values("mean", ascending=False))


def importance_plot(imp, color, title, unit, top_n=10):
    """One dot per CV fold, a diamond for the mean, and the number of folds
    where shuffling the feature made predictions worse."""
    stats = importance_table(imp)
    top = stats.head(top_n).index[::-1]   # largest ends up at the top

    fig = go.Figure()
    for feat in top:
        fig.add_scatter(x=imp[feat], y=[feat] * len(imp), mode="markers", showlegend=False,
                        marker=dict(size=9, color=color, opacity=0.35,
                                    line=dict(width=1, color=SURFACE)),
                        hovertemplate="%{y}<br>fold: %{x:.3f}<extra></extra>")

    fig.add_scatter(x=stats.loc[top, "mean"], y=list(top), mode="markers", showlegend=False,
                    marker=dict(size=14, color=color, symbol="diamond",
                                line=dict(width=1.5, color=SURFACE)),
                    hovertemplate="%{y}<br><b>mean: %{x:.3f}</b><extra></extra>")

    fig.add_vline(x=0, line_width=1.5, line_color=MUTED)
    for feat in top:
        fig.add_annotation(x=1.02, xref="paper", y=feat, showarrow=False,
                           text=f"{stats.loc[feat, 'folds_positive']}/{len(imp)}",
                           font=dict(size=11, color=MUTED))

    fig.update_layout(
        title=f"{title}: permutation importance across {len(imp)} grouped CV folds"
              f"<br><sub>{unit} when the feature is shuffled · diamond = mean · "
              "right column = folds where shuffling hurt</sub>",
        xaxis=dict(title=unit, gridcolor="#eceae5", zeroline=False),
        yaxis=dict(gridcolor="rgba(0,0,0,0)"),
        plot_bgcolor=SURFACE, paper_bgcolor=SURFACE,
        margin=dict(l=210, r=70, t=80, b=50), height=430,
    )
    return fig

## 1. Predicting union density

Besides the economic and V-Dem features, this section uses four predictors taken from the union-density literature (`UNION_ONLY`; sections 2 and 3 don't use them):

| Column | Source | Stands in for |
|---|---|---|
| `ghent` | hand-coded: Denmark, Finland, Iceland, Sweden, Belgium | Ghent system — union-linked unemployment insurance |
| `state_mass_org_engagement` | V-Dem `v2castate` | state-run unionism, as opposed to independent unions |
| `regime_support_working_class` | V-Dem `v2regsupgroups_9` | labour's political power |
| `govt_ideology_socialist` | V-Dem `v2exl_legitideolcr_1` | left government (partial proxy) |

In [4]:
X_train_u = scale(cols_union)
y_train_u = train.loc[X_train_u.index, "union_density"]

In [5]:
ols_union = OLS(y_train_u, add_constant(X_train_u)).fit(
    cov_type="cluster", cov_kwds={"groups": train.loc[X_train_u.index, "iso3"]}
)
print(ols_union.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          union_density   R-squared:                       0.798
Model:                            OLS   Adj. R-squared:                  0.787
Method:                 Least Squares   F-statistic:                     178.4
Date:                Sat, 03 Oct 2026   Prob (F-statistic):           5.23e-63
Time:                        19:14:34   Log-Likelihood:                -2721.6
No. Observations:                 787   AIC:                             5523.
Df Residuals:                     747   BIC:                             5710.
Df Model:                          39
Covariance Type:              cluster
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                              23.6168      0.839     28.163      0.000      21.973      25.260
year                               -2.2806      0.750     -3.040      0.002      -3.751      -0.810
manufacturing_va_pct_gdp           -3.0991      1.258     -2.463      0.014      -5.565      -0.633
industry_va_pct_gdp                 2.1680      1.265      1.714      0.086      -0.311       4.647
agriculture_va_pct_gdp             -5.5918      2.232     -2.506      0.012      -9.966      -1.218
emp_industry_pct                   -3.9489      1.663     -2.375      0.018      -7.208      -0.690
emp_agriculture_pct                -4.7491      3.092     -1.536      0.125     -10.810       1.312
lfp_rate                           -5.1885      2.607     -1.991      0.047     -10.297      -0.080
lfp_rate_female                     5.2600      2.448      2.149      0.032       0.463      10.057
vulnerable_emp_pct                 -2.0071      3.021     -0.664      0.506      -7.929       3.915
unemployment_rate                   0.2726      0.808      0.337      0.736      -1.311       1.857
labor_force_total                   3.5669      1.031      3.458      0.001       1.545       5.588
urban_pop_pct                      -1.9208      1.934     -0.993      0.321      -5.711       1.869
trade_pct_gdp                      -1.0330      1.374     -0.752      0.452      -3.727       1.661
fdi_inflows_pct_gdp                 1.9662      0.607      3.239      0.001       0.776       3.156
manuf_exports_pct                  -2.7902      1.185     -2.354      0.019      -5.113      -0.467
gdp_pc_const                        2.8777      2.058      1.398      0.162      -1.156       6.911
gdp_growth                         -0.1881      0.487     -0.386      0.699      -1.143       0.766
inflation_cpi                       2.1723      0.586      3.706      0.000       1.023       3.321
tax_revenue_pct_gdp                 2.5179      1.669      1.509      0.131      -0.753       5.789
govt_consumption_pct_gdp           -3.1556      1.434     -2.201      0.028      -5.966      -0.345
educ_spend_pct_gdp                  2.1166      1.081      1.958      0.050      -0.002       4.235
health_spend_pct_gdp               -0.8983      2.321     -0.387      0.699      -5.447       3.650
age_dependency_ratio               -1.8217      1.500     -1.215      0.224      -4.761       1.118
upper_secondary_attain_pct         -2.3079      1.613     -1.431      0.153      -5.470       0.854
tertiary_enroll_gross              -3.5145      1.483     -2.370      0.018      -6.421      -0.608
migrant_stock_pct                  -1.9606      1.461     -1.342      0.180      -4.825       0.904
gini                               -5.6056      1.731     -3.239      0.001      -8.998      -2.213
freedom_of_association              4.4168      2.486      1.776      0.076      -0.456       9.290
civil_society_index                -2.3243      4.016     -0.579      0.563     -10.196       5.548
electoral_democracy               -11.1944      3.070     -3.646      0.000     -17.212      -5.177
cso_repression                      2.3629      2.109      1.120      0.263      -1.772       6.497
cso_entry_exit                      1.4370      2.818      0.510      0.610      -4.085       6.959
egalitarian_component               5.7545      4.537      1.268      0.205      -3.138      14.646
equal_resource_distribution        -0.0343      3.815     -0.009      0.993      -7.511       7.442
power_by_socioeconomic_position    -1.8908      1.478     -1.279      0.201      -4.788       1.007
state_mass_org_engagement          -0.9970      1.576     -0.633      0.527      -4.086       2.092
regime_support_working_class       -1.5675      1.217     -1.288      0.198      -3.952       0.818
govt_ideology_socialist             2.0116      0.800      2.514      0.012       0.444       3.580
ghent                               7.9275      1.082      7.329      0.000       5.807      10.048
==============================================================================
Omnibus:                       22.220   Durbin-Watson:                   0.526
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               28.883
Skew:                           0.300   Prob(JB):                     5.35e-07
Kurtosis:                       3.721   Cond. No.                         36.4
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (CRV1)

In [6]:
union_df = df.dropna(subset=cols_union)
cv_union, imp_union = nested_cv(union_df[cols_union], union_df["union_density"], union_df["iso3"])

nested 5-fold grouped CV, 3 repeats, 995 rows / 100 countries

                 RMSE            MAE            R2
                 mean    std    mean    std   mean    std
model
baseline       20.332  0.186  15.814  0.156 -0.052  0.019
OLS            13.698  0.912  11.209  0.602  0.521  0.064
random forest  12.173  0.556   9.867  0.368  0.623  0.035

forest beat OLS in 3 of 3 repeats

forest settings chosen in the 15 outer folds (7 different combinations); most common:
{'max_features': 0.5, 'max_samples': None, 'min_samples_leaf': 2}    4
{'max_features': 0.5, 'max_samples': 0.7, 'min_samples_leaf': 2}     4
{'max_features': 0.2, 'max_samples': 0.7, 'min_samples_leaf': 1}     2

In [7]:
importance_table(imp_union).round(3)

                                  mean     sd  folds_positive
ghent                            3.014  2.471              14
gini                             0.715  0.576              13
educ_spend_pct_gdp               0.706  0.600              14
tax_revenue_pct_gdp              0.608  0.425              14
egalitarian_component            0.424  0.370              14
labor_force_total                0.248  0.331              13
power_by_socioeconomic_position  0.232  0.193              14
equal_resource_distribution      0.188  0.169              14
manufacturing_va_pct_gdp         0.161  0.162              14
civil_society_index              0.098  0.180               9
gdp_pc_const                     0.071  0.172              11
govt_consumption_pct_gdp         0.066  0.130               9
upper_secondary_attain_pct       0.064  0.059              14
state_mass_org_engagement        0.063  0.211               7
age_dependency_ratio             0.060  0.078              10
vulnerable_emp_pct               0.059  0.101              13
year                             0.047  0.041              14
agriculture_va_pct_gdp           0.043  0.167               9
unemployment_rate                0.042  0.054              11
electoral_democracy              0.033  0.081               9
trade_pct_gdp                    0.032  0.080              10
cso_entry_exit                   0.032  0.109              10
lfp_rate                         0.024  0.069              10
freedom_of_association           0.023  0.076              11
migrant_stock_pct                0.022  0.050              10
lfp_rate_female                  0.021  0.055              10
govt_ideology_socialist          0.020  0.045              10
emp_agriculture_pct              0.017  0.066               8
regime_support_working_class     0.012  0.175               7
tertiary_enroll_gross            0.011  0.042              10
health_spend_pct_gdp             0.010  0.063               8
manuf_exports_pct                0.010  0.093               8
fdi_inflows_pct_gdp              0.003  0.079              11
gdp_growth                      -0.002  0.008               8
inflation_cpi                   -0.007  0.063              11
industry_va_pct_gdp             -0.009  0.058               6
cso_repression                  -0.011  0.050               8
urban_pop_pct                   -0.017  0.107               8
emp_industry_pct                -0.019  0.062               5

In [8]:
importance_plot(imp_union, BLUE, "Union density", "RMSE points lost")

## 2. Predicting electoral democracy

Same models and charts as section 1, with V-Dem's `electoral_democracy` (0–1) as the target and `union_density` as one of the predictors. The four `DEM_INGREDIENTS` features are left out because V-Dem builds `electoral_democracy` from them.

In [9]:
X_train_d = scale(cols_dem)
y_train_d = train["electoral_democracy"]

In [10]:
ols_dem = OLS(y_train_d, add_constant(X_train_d)).fit(
    cov_type="cluster", cov_kwds={"groups": train["iso3"]}
)
print(ols_dem.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     electoral_democracy   R-squared:                       0.893
Model:                             OLS   Adj. R-squared:                  0.888
Method:                  Least Squares   F-statistic:                     118.3
Date:                 Sat, 03 Oct 2026   Prob (F-statistic):           2.47e-54
Time:                         19:19:42   Log-Likelihood:                 959.52
No. Observations:                  787   AIC:                            -1855.
Df Residuals:                      755   BIC:                            -1706.
Df Model:                           31
Covariance Type:               cluster
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                               0.7080      0.007     96.412      0.000       0.694       0.722
year                               -0.0251      0.009     -2.845      0.004      -0.042      -0.008
union_density                      -0.0227      0.009     -2.636      0.008      -0.040      -0.006
manufacturing_va_pct_gdp           -0.0090      0.013     -0.678      0.497      -0.035       0.017
industry_va_pct_gdp                -0.0147      0.013     -1.107      0.268      -0.041       0.011
agriculture_va_pct_gdp             -0.0821      0.019     -4.375      0.000      -0.119      -0.045
emp_industry_pct                   -0.0145      0.019     -0.751      0.453      -0.052       0.023
emp_agriculture_pct                -0.0721      0.044     -1.642      0.101      -0.158       0.014
lfp_rate                            0.0539      0.021      2.524      0.012       0.012       0.096
lfp_rate_female                    -0.0423      0.025     -1.715      0.086      -0.091       0.006
vulnerable_emp_pct                  0.0187      0.033      0.564      0.573      -0.046       0.084
unemployment_rate                9.699e-05      0.008      0.012      0.990      -0.016       0.016
labor_force_total                  -0.0109      0.008     -1.343      0.179      -0.027       0.005
urban_pop_pct                      -0.0077      0.014     -0.569      0.569      -0.034       0.019
trade_pct_gdp                       0.0065      0.010      0.655      0.512      -0.013       0.026
fdi_inflows_pct_gdp                -0.0069      0.003     -2.107      0.035      -0.013      -0.000
manuf_exports_pct                  -0.0013      0.013     -0.098      0.922      -0.028       0.025
gdp_pc_const                       -0.0431      0.019     -2.251      0.024      -0.081      -0.006
gdp_growth                         -0.0082      0.005     -1.693      0.090      -0.018       0.001
inflation_cpi                       0.0043      0.006      0.684      0.494      -0.008       0.017
tax_revenue_pct_gdp                -0.0012      0.010     -0.116      0.907      -0.021       0.019
govt_consumption_pct_gdp           -0.0530      0.017     -3.116      0.002      -0.086      -0.020
educ_spend_pct_gdp                  0.0166      0.010      1.679      0.093      -0.003       0.036
health_spend_pct_gdp                0.0553      0.016      3.474      0.001       0.024       0.087
age_dependency_ratio                0.0047      0.015      0.320      0.749      -0.024       0.034
upper_secondary_attain_pct          0.0172      0.012      1.385      0.166      -0.007       0.042
tertiary_enroll_gross              -0.0205      0.018     -1.109      0.267      -0.057       0.016
migrant_stock_pct                  -0.0170      0.013     -1.359      0.174      -0.042       0.008
gini                               -0.0100      0.012     -0.836      0.403      -0.034       0.013
egalitarian_component               0.3268      0.030     10.886      0.000       0.268       0.386
equal_resource_distribution        -0.2096      0.027     -7.765      0.000      -0.262      -0.157
power_by_socioeconomic_position     0.0016      0.014      0.113      0.910      -0.026       0.029
==============================================================================
Omnibus:                       39.158   Durbin-Watson:                   0.492
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.118
Skew:                          -0.446   Prob(JB):                     2.92e-12
Kurtosis:                       3.908   Cond. No.                         22.2
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (CRV1)

In [11]:
cv_dem, imp_dem = nested_cv(df[cols_dem], df["electoral_democracy"], df["iso3"])

nested 5-fold grouped CV, 3 repeats, 995 rows / 100 countries

                RMSE           MAE            R2
                mean    std   mean    std   mean    std
model
baseline       0.212  0.001  0.174  0.001 -0.032  0.015
OLS            0.118  0.026  0.081  0.008  0.667  0.148
random forest  0.131  0.004  0.087  0.003  0.603  0.026

forest beat OLS in 1 of 3 repeats

forest settings chosen in the 15 outer folds (10 different combinations); most common:
{'max_features': 0.2, 'max_samples': None, 'min_samples_leaf': 2}    4
{'max_features': 0.2, 'max_samples': 0.7, 'min_samples_leaf': 1}     3
{'max_features': 0.5, 'max_samples': None, 'min_samples_leaf': 1}    1

In [12]:
importance_table(imp_dem).round(3)

                                  mean     sd  folds_positive
egalitarian_component            0.046  0.030              15
power_by_socioeconomic_position  0.009  0.004              15
gdp_pc_const                     0.005  0.005              12
emp_agriculture_pct              0.004  0.007              13
equal_resource_distribution      0.003  0.004              13
emp_industry_pct                 0.003  0.002              15
health_spend_pct_gdp             0.002  0.004              10
agriculture_va_pct_gdp           0.002  0.004               9
gini                             0.002  0.003              10
migrant_stock_pct                0.001  0.003              13
manuf_exports_pct                0.001  0.001              13
age_dependency_ratio             0.001  0.001               9
vulnerable_emp_pct               0.001  0.001              10
govt_consumption_pct_gdp         0.000  0.001               8
urban_pop_pct                    0.000  0.005               9
union_density                    0.000  0.001              11
inflation_cpi                    0.000  0.000              12
trade_pct_gdp                    0.000  0.001               9
year                             0.000  0.000               9
lfp_rate_female                  0.000  0.001               9
manufacturing_va_pct_gdp         0.000  0.002               9
unemployment_rate               -0.000  0.000               4
educ_spend_pct_gdp              -0.000  0.000               9
fdi_inflows_pct_gdp             -0.000  0.000               7
upper_secondary_attain_pct      -0.000  0.001               6
gdp_growth                      -0.000  0.000               7
tax_revenue_pct_gdp             -0.000  0.001               4
industry_va_pct_gdp             -0.000  0.002               9
tertiary_enroll_gross           -0.000  0.001               6
lfp_rate                        -0.000  0.001               3
labor_force_total               -0.002  0.002               2

In [13]:
importance_plot(imp_dem, ORANGE, "Electoral democracy", "RMSE lost (index, 0–1)")

## 3. Predicting electoral democracy without V-Dem predictors

Section 2 again, but with every V-Dem column (`VDEM_COLS`) removed from the predictors — including the three equality indices, which carried most of section 2's importance and are themselves V-Dem democracy indices rated by the same experts. What's left is World Bank variables plus `union_density`, so this is the cleanest test of whether economic structure and unions predict democracy.

In [14]:
X_train_nv = scale(cols_dem_novdem)
y_train_nv = train["electoral_democracy"]

In [15]:
ols_novdem = OLS(y_train_nv, add_constant(X_train_nv)).fit(
    cov_type="cluster", cov_kwds={"groups": train["iso3"]}
)
print(ols_novdem.summary())

                             OLS Regression Results
===============================================================================
Dep. Variable:     electoral_democracy   R-squared:                       0.723
Model:                             OLS   Adj. R-squared:                  0.712
Method:                  Least Squares   F-statistic:                     20.88
Date:                 Sat, 03 Oct 2026   Prob (F-statistic):           4.54e-26
Time:                         19:23:51   Log-Likelihood:                 585.83
No. Observations:                  787   AIC:                            -1114.
Df Residuals:                      758   BIC:                            -978.3
Df Model:                           28
Covariance Type:               cluster
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                          0.7080      0.013     56.385      0.000       0.683       0.733
year                          -0.0517      0.012     -4.374      0.000      -0.075      -0.029
union_density                 -0.0490      0.017     -2.852      0.004      -0.083      -0.015
manufacturing_va_pct_gdp      -0.0205      0.022     -0.932      0.351      -0.064       0.023
industry_va_pct_gdp           -0.0441      0.021     -2.105      0.035      -0.085      -0.003
agriculture_va_pct_gdp        -0.1154      0.041     -2.784      0.005      -0.197      -0.034
emp_industry_pct              -0.0061      0.029     -0.213      0.831      -0.063       0.050
emp_agriculture_pct           -0.1579      0.058     -2.741      0.006      -0.271      -0.045
lfp_rate                       0.0013      0.031      0.042      0.967      -0.060       0.062
lfp_rate_female                0.0102      0.036      0.286      0.775      -0.060       0.081
vulnerable_emp_pct             0.1715      0.045      3.775      0.000       0.082       0.261
unemployment_rate              0.0403      0.012      3.295      0.001       0.016       0.064
labor_force_total             -0.0094      0.014     -0.667      0.505      -0.037       0.018
urban_pop_pct                  0.0027      0.020      0.133      0.895      -0.037       0.042
trade_pct_gdp                  0.0070      0.018      0.399      0.690      -0.028       0.042
fdi_inflows_pct_gdp           -0.0019      0.004     -0.452      0.652      -0.010       0.006
manuf_exports_pct             -0.0059      0.022     -0.272      0.785      -0.048       0.036
gdp_pc_const                   0.0443      0.032      1.373      0.170      -0.019       0.108
gdp_growth                     0.0095      0.008      1.223      0.221      -0.006       0.025
inflation_cpi                  0.0058      0.012      0.469      0.639      -0.018       0.030
tax_revenue_pct_gdp            0.0117      0.017      0.683      0.495      -0.022       0.045
govt_consumption_pct_gdp      -0.0776      0.025     -3.071      0.002      -0.127      -0.028
educ_spend_pct_gdp             0.0517      0.018      2.893      0.004       0.017       0.087
health_spend_pct_gdp           0.0845      0.028      3.036      0.002       0.030       0.139
age_dependency_ratio           0.0296      0.025      1.169      0.242      -0.020       0.079
upper_secondary_attain_pct     0.0198      0.021      0.959      0.337      -0.021       0.060
tertiary_enroll_gross          0.0006      0.024      0.027      0.979      -0.046       0.047
migrant_stock_pct             -0.0449      0.022     -2.025      0.043      -0.088      -0.001
gini                          -0.0444      0.024     -1.858      0.063      -0.091       0.002
==============================================================================
Omnibus:                       24.628   Durbin-Watson:                   0.363
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               26.096
Skew:                          -0.433   Prob(JB):                     2.15e-06
Kurtosis:                       3.215   Cond. No.                         16.4
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (CRV1)

In [16]:
cv_novdem, imp_novdem = nested_cv(df[cols_dem_novdem], df["electoral_democracy"], df["iso3"])

nested 5-fold grouped CV, 3 repeats, 995 rows / 100 countries

                RMSE           MAE            R2
                mean    std   mean    std   mean    std
model
baseline       0.212  0.001  0.174  0.001 -0.032  0.015
OLS            0.170  0.014  0.120  0.003  0.328  0.115
random forest  0.151  0.002  0.102  0.001  0.474  0.015

forest beat OLS in 3 of 3 repeats

forest settings chosen in the 15 outer folds (9 different combinations); most common:
{'max_features': 0.2, 'max_samples': 0.7, 'min_samples_leaf': 1}     5
{'max_features': 0.2, 'max_samples': 0.7, 'min_samples_leaf': 2}     2
{'max_features': 0.2, 'max_samples': None, 'min_samples_leaf': 1}    2

In [17]:
importance_table(imp_novdem).round(3)

                             mean     sd  folds_positive
gdp_pc_const                0.014  0.011              13
health_spend_pct_gdp        0.007  0.007              13
agriculture_va_pct_gdp      0.006  0.006              14
emp_agriculture_pct         0.003  0.005              13
emp_industry_pct            0.001  0.001              13
unemployment_rate           0.000  0.001              11
vulnerable_emp_pct          0.000  0.002               9
year                        0.000  0.000              13
inflation_cpi               0.000  0.000              14
educ_spend_pct_gdp          0.000  0.001               8
manuf_exports_pct           0.000  0.001               8
union_density               0.000  0.001               9
age_dependency_ratio        0.000  0.001               5
manufacturing_va_pct_gdp   -0.000  0.002               8
fdi_inflows_pct_gdp        -0.000  0.000               6
urban_pop_pct              -0.000  0.006               7
industry_va_pct_gdp        -0.000  0.002               7
gdp_growth                 -0.000  0.000               6
tertiary_enroll_gross      -0.000  0.001               7
upper_secondary_attain_pct -0.000  0.001               7
govt_consumption_pct_gdp   -0.000  0.001               6
gini                       -0.000  0.001               2
trade_pct_gdp              -0.000  0.001               6
tax_revenue_pct_gdp        -0.000  0.001               6
migrant_stock_pct          -0.001  0.003               7
labor_force_total          -0.001  0.002               5
lfp_rate_female            -0.001  0.001               5
lfp_rate                   -0.001  0.001               1

In [18]:
importance_plot(imp_novdem, GREEN, "Electoral democracy, no V-Dem", "RMSE lost (index, 0–1)")